[package]
name = "longtail"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.69.4"

[dependencies]
itertools = "0.13.0"
num_cpus = "1.16.0"
strum = { version = "0.26.2", features = ["derive"] }
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
