name: "Test Suite"
on:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-linux:
    name: linux - cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: |
          pushd test-data
          ./mkdata.sh

      - run: cargo test

  test-windows:
    name: windows - cargo test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: |
          pushd test-data
          ./mkdata.ps1

      - run: cargo test

  # Check formatting with rustfmt
  formatting:
    name: common - cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

      - name: Clippy
        run: cargo clippy

      - name: Clippy of tests
        run: cargo clippy --tests
